model:
  model_name: ettm1
  seq_length: 200
  diff_num_steps: 200
  stride: 1

  context_dim: 7 # prior dim
  point_dim: 7 # future dim
  context_dim_out: 7 # encoded context dim
  feature_dim: 64 # shared space dim


solver:
  num_epochs: 200
  learning_rate: 0.001
  eval_each: 100

dataloader:
  dataset_path: ./Datas/Public_datas/ETTm1_dataset.h5
  matrix_path: ./Datas/Public_datas/ETTm1_metrix.h5
  train_batch_size: 32
  eval_batch_size: 32

  # train_list: [2,3,4,5,6,7,8,9,10]
  # eval_list: [1,11]
  # test_list: [12,13,14]
  window_size: 368
  step_size_train: 1
  step_size_eval: 16
  step_size_test: 16
  overlap: 32
  prior_size: 200 # history data for condition
  future_size: 168