model:
  model_name: gaussian_unet_generate
  seq_length: 256
  diff_num_steps: 300
  stride: 1

  context_dim: 6 # prior dim
  point_dim: 6 # future dim
  context_dim_out: 6 # encoded context dim
  feature_dim: 64 # shared space dim


solver:
  num_epochs: 100
  learning_rate: 0.001
  eval_each: 20

dataloader:
  dataset_path: ./Datas/USC_HAD_dataset.h5
  matrix_path: ./Datas/USC_HAD_matrix_generate.h5
  train_batch_size: 32
  eval_batch_size: 32

  train_list: [2,3,4,5,6,7,8,9,10]
  eval_list: [1,11]
  test_list: [12,13,14]
  window_size: 256
  step_size: 256
  prior_size: 64 # history data for condition
  future_size: 64