model:
  model_name: uschad_gen_activity
  seq_length: 200
  diff_num_steps: 500
  stride: 1

  context_dim: 6 # prior dim
  point_dim: 6 # future dim
  context_dim_out: 6 # encoded context dim
  feature_dim: 64 # shared space dim


solver:
  num_epochs: 2000
  learning_rate: 1.0e-3
  eval_each: 400

dataloader:
  dataset_path: ../Datas/uschad_activity_dataset.h5
  train_batch_size: 256
  eval_batch_size: 1024

  window_size: 200
  # step_size: 24

  # result_folder: ../Experiments_100_genbylabel/

